import { Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import Footer from "../components/shared/Footer.jsx";
import WorkoutsProvider from "../context/WorkoutsContext.jsx";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "FitLog-Workout Library",
  description: "Generated by Fitlog-Workout Librar",
};

export default function RootLayout({ children }) {
  return (
    <html
  lang="en"
  data-theme="dark"
  className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${oswald.variable} h-full antialiased`}
>
      <body className="min-h-full flex flex-col">
        <WorkoutsProvider>
          <Navbar></Navbar>
          <div>
            {children}
          </div>
          <Footer></Footer>
          <ToastContainer></ToastContainer>
        </WorkoutsProvider>
      </body>
    </html>
  );
}
